name: Schedual Lunch

on:
  schedule:
  - cron: '0 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update lunch
      run: bash ./update_lunch.sh 
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
